POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ac534dd6-0a9a-4f9a-9d5a-b77c40adf201"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "f70f5ac5-0ce9-47f7-a17b-0a6b862720a9",
    "account_id_to": "8c647ed5-d414-4904-9626-d52b69dfe1bc",
    "amount": 33
}
