POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ac534dd6-0a9a-4f9a-9d5a-b77c40adf201"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "ed5bec8a-fadf-426a-a090-8b2235da4276",
    "account_id_to": "a1f7e7d8-f8dc-47ba-a89c-faf1c363d79c",
    "amount": 20
}
